#!/bin/bash

sueldo_en_usd=$SUELDO_EN_USD

dolar_venta=$(curl -s https://api-dolar-argentina.herokuapp.com/api/dolarblue | jq -r '.venta')
dolar_compra=$(curl -s https://api-dolar-argentina.herokuapp.com/api/dolarblue | jq -r '.compra')
sueldito=$(echo "scale=0; $sueldo_en_usd * $dolar_compra / 1" | bc -l)

echo "<span foreground=\"#888800\">\$$sueldito</span> <span foreground=\"#666666\">(</span><span foreground=\"#6060AA\">\$$dolar_compra</span><span foreground=\"#666666\">/</span><span foreground=\"#4040AA\">\$$dolar_venta</span><span foreground=\"#666666\">)</span>"
