#!/bin/bash

FERIADOS_DATES="$SCRIPT_DIR/feriados/feriados-dates"
if [ ! -f $FERIADOS_DATES ]; then exit; fi

feriados=($(cat $FERIADOS_DATES))
current_date=$(date +%s)

for date in "${feriados[@]}"; do
    if [[ $current_date -le $date ]]; then
       echo $((($date - $current_date) / 86400 + 1))
       break
    fi
done
