#!/bin/bash

apikey="[insert your bcra apikey here]"
color=#00AA00
price=\$$(curl -s https://api.estadisticasbcra.com/usd_of_minorista -H "Authorization: Bearer $apikey" | jq '.[-1].v')
message="<span foreground=\"$color\">$price</span>" 
echo $message