#!/bin/bash

if [ ! -f "$SCRIPT_DIR/countdown/date" ]; then exit; fi
START=$1
time_left=$(eval "echo $(date -ud "@$(($(date -d "$(cat $SCRIPT_DIR/countdown/date)" +%s) - $(date +%s))) " +'$((%s/86400))d')")
echo $time_left
